/**
 * State-level DV coalitions. One entry per US state + DC.
 * Extend by adding to STATE_RESOURCES — the resources page renders whatever is here.
 */
export interface StateResource {
  name: string;
  url: string;
  phone?: string;
  resourceOwner: string;
  jurisdiction: string;
  issueCovered: string;
  /** null = not individually re-verified by us. Never fill this in without a real check. */
  dateLastChecked: string | null;
  safeDeviceWarning: string;
  humanContactMethod: string;
}

export const US_STATES: { code: string; name: string }[] = [
  { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" }, { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" }, { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" }, { code: "DC", name: "District of Columbia" },
  { code: "FL", name: "Florida" }, { code: "GA", name: "Georgia" }, { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" }, { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" }, { code: "KS", name: "Kansas" }, { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" }, { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" }, { code: "MI", name: "Michigan" }, { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" }, { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" }, { code: "NV", name: "Nevada" }, { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" }, { code: "NM", name: "New Mexico" }, { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" }, { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" }, { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" }, { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" }, { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" }, { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" }, { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" },
];

export const STATE_RESOURCES: Record<string, StateResource[]> = {
  AL: [{
    name: "Alabama Coalition Against Domestic Violence",
    url: "https://www.acadv.org",
    phone: "1-800-650-6522",
    resourceOwner: "Alabama Coalition Against Domestic Violence",
    jurisdiction: "AL",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  AK: [{
    name: "Alaska Network on Domestic Violence and Sexual Assault",
    url: "https://andvsa.org",
    resourceOwner: "Alaska Network on Domestic Violence and Sexual Assault",
    jurisdiction: "AK",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  AZ: [{
    name: "Arizona Coalition to End Sexual and Domestic Violence",
    url: "https://www.acesdv.org",
    phone: "1-800-782-6400",
    resourceOwner: "Arizona Coalition to End Sexual and Domestic Violence",
    jurisdiction: "AZ",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  AR: [{
    name: "Arkansas Coalition Against Domestic Violence",
    url: "https://www.domesticpeace.com",
    phone: "1-800-269-4668",
    resourceOwner: "Arkansas Coalition Against Domestic Violence",
    jurisdiction: "AR",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  CA: [{
    name: "California Partnership to End Domestic Violence",
    url: "https://www.cpedv.org",
    resourceOwner: "California Partnership to End Domestic Violence",
    jurisdiction: "CA",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  CO: [{
    name: "Violence Free Colorado",
    url: "https://www.violencefreecolorado.org",
    resourceOwner: "Violence Free Colorado",
    jurisdiction: "CO",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  CT: [{
    name: "Connecticut Coalition Against Domestic Violence",
    url: "https://www.ctcadv.org",
    phone: "1-888-774-2900",
    resourceOwner: "Connecticut Coalition Against Domestic Violence",
    jurisdiction: "CT",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  DE: [{
    name: "Delaware Coalition Against Domestic Violence",
    url: "https://dcadv.org",
    resourceOwner: "Delaware Coalition Against Domestic Violence",
    jurisdiction: "DE",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  DC: [{
    name: "DC Coalition Against Domestic Violence",
    url: "https://dccadv.org",
    resourceOwner: "DC Coalition Against Domestic Violence",
    jurisdiction: "DC",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  FL: [{
    name: "Florida Coalition Against Domestic Violence",
    url: "https://www.myflfamilies.com/services/domestic-violence",
    phone: "1-800-500-1119",
    resourceOwner: "Florida Coalition Against Domestic Violence",
    jurisdiction: "FL",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  GA: [{
    name: "Georgia Coalition Against Domestic Violence",
    url: "https://gcadv.org",
    phone: "1-800-334-2836",
    resourceOwner: "Georgia Coalition Against Domestic Violence",
    jurisdiction: "GA",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  HI: [{
    name: "Hawaii State Coalition Against Domestic Violence",
    url: "https://www.hscadv.org",
    resourceOwner: "Hawaii State Coalition Against Domestic Violence",
    jurisdiction: "HI",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  ID: [{
    name: "Idaho Coalition Against Sexual and Domestic Violence",
    url: "https://www.idvsa.org",
    resourceOwner: "Idaho Coalition Against Sexual and Domestic Violence",
    jurisdiction: "ID",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  IL: [{
    name: "The Network: Advocating Against Domestic Violence (Illinois)",
    url: "https://www.the-network.org",
    resourceOwner: "The Network: Advocating Against Domestic Violence (Illinois)",
    jurisdiction: "IL",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  IN: [{
    name: "Indiana Coalition Against Domestic Violence",
    url: "https://www.icadvinc.org",
    phone: "1-800-332-7385",
    resourceOwner: "Indiana Coalition Against Domestic Violence",
    jurisdiction: "IN",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  IA: [{
    name: "Iowa Coalition Against Domestic Violence",
    url: "https://www.icadv.org",
    phone: "1-800-770-1650",
    resourceOwner: "Iowa Coalition Against Domestic Violence",
    jurisdiction: "IA",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  KS: [{
    name: "Kansas Coalition Against Sexual and Domestic Violence",
    url: "https://www.kcsdv.org",
    resourceOwner: "Kansas Coalition Against Sexual and Domestic Violence",
    jurisdiction: "KS",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  KY: [{
    name: "ZeroV (Kentucky Coalition Against Domestic Violence)",
    url: "https://zerov.org",
    resourceOwner: "ZeroV (Kentucky Coalition Against Domestic Violence)",
    jurisdiction: "KY",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  LA: [{
    name: "Louisiana Coalition Against Domestic Violence",
    url: "https://lcadv.org",
    resourceOwner: "Louisiana Coalition Against Domestic Violence",
    jurisdiction: "LA",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  ME: [{
    name: "Maine Coalition to End Domestic Violence",
    url: "https://www.mcedv.org",
    phone: "1-866-834-4357",
    resourceOwner: "Maine Coalition to End Domestic Violence",
    jurisdiction: "ME",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  MD: [{
    name: "Maryland Network Against Domestic Violence",
    url: "https://mnadv.org",
    phone: "1-800-634-3577",
    resourceOwner: "Maryland Network Against Domestic Violence",
    jurisdiction: "MD",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  MA: [{
    name: "Jane Doe Inc. — Massachusetts Coalition Against Sexual Assault and Domestic Violence",
    url: "https://janedoe.org",
    resourceOwner: "Jane Doe Inc. — Massachusetts Coalition Against Sexual Assault and Domestic Violence",
    jurisdiction: "MA",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  MI: [{
    name: "Michigan Coalition to End Domestic and Sexual Violence",
    url: "https://mcedsv.org",
    resourceOwner: "Michigan Coalition to End Domestic and Sexual Violence",
    jurisdiction: "MI",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  MN: [{
    name: "Violence Free Minnesota",
    url: "https://www.vfmn.org",
    phone: "1-866-223-1111",
    resourceOwner: "Violence Free Minnesota",
    jurisdiction: "MN",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  MS: [{
    name: "Mississippi Coalition Against Domestic Violence",
    url: "https://mcadv.org",
    phone: "1-800-898-3234",
    resourceOwner: "Mississippi Coalition Against Domestic Violence",
    jurisdiction: "MS",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  MO: [{
    name: "Missouri Coalition Against Domestic and Sexual Violence",
    url: "https://www.mocadsv.org",
    resourceOwner: "Missouri Coalition Against Domestic and Sexual Violence",
    jurisdiction: "MO",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  MT: [{
    name: "Montana Coalition Against Domestic and Sexual Violence",
    url: "https://mcadsv.com",
    resourceOwner: "Montana Coalition Against Domestic and Sexual Violence",
    jurisdiction: "MT",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  NE: [{
    name: "Nebraska Coalition to End Sexual and Domestic Violence",
    url: "https://www.nebraskacoalition.org",
    resourceOwner: "Nebraska Coalition to End Sexual and Domestic Violence",
    jurisdiction: "NE",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  NV: [{
    name: "Nevada Coalition to End Domestic and Sexual Violence",
    url: "https://www.ncedsv.org",
    resourceOwner: "Nevada Coalition to End Domestic and Sexual Violence",
    jurisdiction: "NV",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  NH: [{
    name: "New Hampshire Coalition Against Domestic and Sexual Violence",
    url: "https://www.nhcadsv.org",
    phone: "1-866-644-3574",
    resourceOwner: "New Hampshire Coalition Against Domestic and Sexual Violence",
    jurisdiction: "NH",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  NJ: [{
    name: "New Jersey Coalition to End Domestic Violence",
    url: "https://njcedv.org",
    phone: "1-800-572-7233",
    resourceOwner: "New Jersey Coalition to End Domestic Violence",
    jurisdiction: "NJ",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  NM: [{
    name: "New Mexico Coalition Against Domestic Violence",
    url: "https://www.nmcadv.org",
    resourceOwner: "New Mexico Coalition Against Domestic Violence",
    jurisdiction: "NM",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  NY: [{
    name: "New York State Coalition Against Domestic Violence",
    url: "https://www.nyscadv.org",
    phone: "1-800-942-6906",
    resourceOwner: "New York State Coalition Against Domestic Violence",
    jurisdiction: "NY",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  NC: [{
    name: "North Carolina Coalition Against Domestic Violence",
    url: "https://nccadv.org",
    resourceOwner: "North Carolina Coalition Against Domestic Violence",
    jurisdiction: "NC",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  ND: [{
    name: "North Dakota Council on Abused Women's Services (CAWS North Dakota)",
    url: "https://www.cawsnorthdakota.org",
    phone: "1-888-255-6240",
    resourceOwner: "North Dakota Council on Abused Women's Services (CAWS North Dakota)",
    jurisdiction: "ND",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  OH: [{
    name: "Ohio Domestic Violence Network",
    url: "https://www.odvn.org",
    phone: "1-800-934-9840",
    resourceOwner: "Ohio Domestic Violence Network",
    jurisdiction: "OH",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  OK: [{
    name: "Oklahoma Coalition Against Domestic Violence and Sexual Assault",
    url: "https://ocadvsa.org",
    resourceOwner: "Oklahoma Coalition Against Domestic Violence and Sexual Assault",
    jurisdiction: "OK",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  OR: [{
    name: "Oregon Coalition Against Domestic and Sexual Violence",
    url: "https://www.ocadsv.org",
    resourceOwner: "Oregon Coalition Against Domestic and Sexual Violence",
    jurisdiction: "OR",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  PA: [{
    name: "Pennsylvania Coalition Against Domestic Violence",
    url: "https://www.pcadv.org",
    phone: "1-800-932-4632",
    resourceOwner: "Pennsylvania Coalition Against Domestic Violence",
    jurisdiction: "PA",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  RI: [{
    name: "Rhode Island Coalition Against Domestic Violence",
    url: "https://www.ricadv.org",
    phone: "1-800-494-8100",
    resourceOwner: "Rhode Island Coalition Against Domestic Violence",
    jurisdiction: "RI",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  SC: [{
    name: "South Carolina Coalition Against Domestic Violence and Sexual Assault",
    url: "https://sccadvasa.org",
    resourceOwner: "South Carolina Coalition Against Domestic Violence and Sexual Assault",
    jurisdiction: "SC",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  SD: [{
    name: "South Dakota Coalition Ending Domestic and Sexual Violence",
    url: "https://www.sdcedsv.org",
    resourceOwner: "South Dakota Coalition Ending Domestic and Sexual Violence",
    jurisdiction: "SD",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  TN: [{
    name: "Tennessee Coalition to End Domestic and Sexual Violence",
    url: "https://tncoalition.org",
    phone: "1-800-289-9018",
    resourceOwner: "Tennessee Coalition to End Domestic and Sexual Violence",
    jurisdiction: "TN",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  TX: [{
    name: "Texas Council on Family Violence",
    url: "https://tcfv.org",
    resourceOwner: "Texas Council on Family Violence",
    jurisdiction: "TX",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  UT: [{
    name: "Utah Domestic Violence Coalition",
    url: "https://www.udvc.org",
    phone: "1-800-897-5465",
    resourceOwner: "Utah Domestic Violence Coalition",
    jurisdiction: "UT",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  VT: [{
    name: "Vermont Network Against Domestic and Sexual Violence",
    url: "https://vtnetwork.org",
    phone: "1-800-228-7395",
    resourceOwner: "Vermont Network Against Domestic and Sexual Violence",
    jurisdiction: "VT",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  VA: [{
    name: "Virginia Sexual and Domestic Violence Action Alliance",
    url: "https://vsdvalliance.org",
    phone: "1-800-838-8238",
    resourceOwner: "Virginia Sexual and Domestic Violence Action Alliance",
    jurisdiction: "VA",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
  WA: [{
    name: "Washington State Coalition Against Domestic Violence",
    url: "https://wscadv.org",
    resourceOwner: "Washington State Coalition Against Domestic Violence",
    jurisdiction: "WA",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  WV: [{
    name: "West Virginia Coalition Against Domestic Violence",
    url: "https://www.wvcadv.org",
    resourceOwner: "West Virginia Coalition Against Domestic Violence",
    jurisdiction: "WV",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  WI: [{
    name: "End Domestic Abuse Wisconsin",
    url: "https://www.endabusewi.org",
    resourceOwner: "End Domestic Abuse Wisconsin",
    jurisdiction: "WI",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Web form",
  }],
  WY: [{
    name: "Wyoming Coalition Against Domestic Violence and Sexual Assault",
    url: "https://www.wyomingdvsa.org",
    phone: "1-800-990-3877",
    resourceOwner: "Wyoming Coalition Against Domestic Violence and Sexual Assault",
    jurisdiction: "WY",
    issueCovered: "Domestic violence — shelter, advocacy, and legal referral",
    dateLastChecked: null,
    safeDeviceWarning: "Call or visit from a device the other person cannot check.",
    humanContactMethod: "Phone",
  }],
};
