/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttorneyTokenRouteImport } from './routes/attorney.$token'
import { Route as AuthenticatedVoiceNotesRouteImport } from './routes/_authenticated/voice-notes'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedOpraHelperRouteImport } from './routes/_authenticated/opra-helper'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLiveRecordingRouteImport } from './routes/_authenticated/live-recording'
import { Route as AuthenticatedLegalDocumentsRouteImport } from './routes/_authenticated/legal-documents'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedEvidenceRouteImport } from './routes/_authenticated/evidence'
import { Route as AuthenticatedEscalationDetectorRouteImport } from './routes/_authenticated/escalation-detector'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCourtPacketRouteImport } from './routes/_authenticated/court-packet'
import { Route as AuthenticatedCaseBuilderRouteImport } from './routes/_authenticated/case-builder'
import { Route as AuthenticatedAttorneyPortalRouteImport } from './routes/_authenticated/attorney-portal'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttorneyTokenRoute = AttorneyTokenRouteImport.update({
  id: '/attorney/$token',
  path: '/attorney/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceNotesRoute = AuthenticatedVoiceNotesRouteImport.update({
  id: '/voice-notes',
  path: '/voice-notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpraHelperRoute = AuthenticatedOpraHelperRouteImport.update({
  id: '/opra-helper',
  path: '/opra-helper',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveRecordingRoute =
  AuthenticatedLiveRecordingRouteImport.update({
    id: '/live-recording',
    path: '/live-recording',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLegalDocumentsRoute =
  AuthenticatedLegalDocumentsRouteImport.update({
    id: '/legal-documents',
    path: '/legal-documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEvidenceRoute = AuthenticatedEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEscalationDetectorRoute =
  AuthenticatedEscalationDetectorRouteImport.update({
    id: '/escalation-detector',
    path: '/escalation-detector',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCourtPacketRoute =
  AuthenticatedCourtPacketRouteImport.update({
    id: '/court-packet',
    path: '/court-packet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaseBuilderRoute =
  AuthenticatedCaseBuilderRouteImport.update({
    id: '/case-builder',
    path: '/case-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttorneyPortalRoute =
  AuthenticatedAttorneyPortalRouteImport.update({
    id: '/attorney-portal',
    path: '/attorney-portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attorney-portal': typeof AuthenticatedAttorneyPortalRoute
  '/case-builder': typeof AuthenticatedCaseBuilderRoute
  '/court-packet': typeof AuthenticatedCourtPacketRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escalation-detector': typeof AuthenticatedEscalationDetectorRoute
  '/evidence': typeof AuthenticatedEvidenceRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/legal-documents': typeof AuthenticatedLegalDocumentsRoute
  '/live-recording': typeof AuthenticatedLiveRecordingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/opra-helper': typeof AuthenticatedOpraHelperRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/voice-notes': typeof AuthenticatedVoiceNotesRoute
  '/attorney/$token': typeof AttorneyTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attorney-portal': typeof AuthenticatedAttorneyPortalRoute
  '/case-builder': typeof AuthenticatedCaseBuilderRoute
  '/court-packet': typeof AuthenticatedCourtPacketRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escalation-detector': typeof AuthenticatedEscalationDetectorRoute
  '/evidence': typeof AuthenticatedEvidenceRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/legal-documents': typeof AuthenticatedLegalDocumentsRoute
  '/live-recording': typeof AuthenticatedLiveRecordingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/opra-helper': typeof AuthenticatedOpraHelperRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/voice-notes': typeof AuthenticatedVoiceNotesRoute
  '/attorney/$token': typeof AttorneyTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/attorney-portal': typeof AuthenticatedAttorneyPortalRoute
  '/_authenticated/case-builder': typeof AuthenticatedCaseBuilderRoute
  '/_authenticated/court-packet': typeof AuthenticatedCourtPacketRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/escalation-detector': typeof AuthenticatedEscalationDetectorRoute
  '/_authenticated/evidence': typeof AuthenticatedEvidenceRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/legal-documents': typeof AuthenticatedLegalDocumentsRoute
  '/_authenticated/live-recording': typeof AuthenticatedLiveRecordingRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/opra-helper': typeof AuthenticatedOpraHelperRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/voice-notes': typeof AuthenticatedVoiceNotesRoute
  '/attorney/$token': typeof AttorneyTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/attorney-portal'
    | '/case-builder'
    | '/court-packet'
    | '/dashboard'
    | '/escalation-detector'
    | '/evidence'
    | '/journal'
    | '/legal-documents'
    | '/live-recording'
    | '/onboarding'
    | '/opra-helper'
    | '/resources'
    | '/settings'
    | '/timeline'
    | '/voice-notes'
    | '/attorney/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/attorney-portal'
    | '/case-builder'
    | '/court-packet'
    | '/dashboard'
    | '/escalation-detector'
    | '/evidence'
    | '/journal'
    | '/legal-documents'
    | '/live-recording'
    | '/onboarding'
    | '/opra-helper'
    | '/resources'
    | '/settings'
    | '/timeline'
    | '/voice-notes'
    | '/attorney/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/attorney-portal'
    | '/_authenticated/case-builder'
    | '/_authenticated/court-packet'
    | '/_authenticated/dashboard'
    | '/_authenticated/escalation-detector'
    | '/_authenticated/evidence'
    | '/_authenticated/journal'
    | '/_authenticated/legal-documents'
    | '/_authenticated/live-recording'
    | '/_authenticated/onboarding'
    | '/_authenticated/opra-helper'
    | '/_authenticated/resources'
    | '/_authenticated/settings'
    | '/_authenticated/timeline'
    | '/_authenticated/voice-notes'
    | '/attorney/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AttorneyTokenRoute: typeof AttorneyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attorney/$token': {
      id: '/attorney/$token'
      path: '/attorney/$token'
      fullPath: '/attorney/$token'
      preLoaderRoute: typeof AttorneyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice-notes': {
      id: '/_authenticated/voice-notes'
      path: '/voice-notes'
      fullPath: '/voice-notes'
      preLoaderRoute: typeof AuthenticatedVoiceNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opra-helper': {
      id: '/_authenticated/opra-helper'
      path: '/opra-helper'
      fullPath: '/opra-helper'
      preLoaderRoute: typeof AuthenticatedOpraHelperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live-recording': {
      id: '/_authenticated/live-recording'
      path: '/live-recording'
      fullPath: '/live-recording'
      preLoaderRoute: typeof AuthenticatedLiveRecordingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/legal-documents': {
      id: '/_authenticated/legal-documents'
      path: '/legal-documents'
      fullPath: '/legal-documents'
      preLoaderRoute: typeof AuthenticatedLegalDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evidence': {
      id: '/_authenticated/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AuthenticatedEvidenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/escalation-detector': {
      id: '/_authenticated/escalation-detector'
      path: '/escalation-detector'
      fullPath: '/escalation-detector'
      preLoaderRoute: typeof AuthenticatedEscalationDetectorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/court-packet': {
      id: '/_authenticated/court-packet'
      path: '/court-packet'
      fullPath: '/court-packet'
      preLoaderRoute: typeof AuthenticatedCourtPacketRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/case-builder': {
      id: '/_authenticated/case-builder'
      path: '/case-builder'
      fullPath: '/case-builder'
      preLoaderRoute: typeof AuthenticatedCaseBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attorney-portal': {
      id: '/_authenticated/attorney-portal'
      path: '/attorney-portal'
      fullPath: '/attorney-portal'
      preLoaderRoute: typeof AuthenticatedAttorneyPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAttorneyPortalRoute: typeof AuthenticatedAttorneyPortalRoute
  AuthenticatedCaseBuilderRoute: typeof AuthenticatedCaseBuilderRoute
  AuthenticatedCourtPacketRoute: typeof AuthenticatedCourtPacketRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEscalationDetectorRoute: typeof AuthenticatedEscalationDetectorRoute
  AuthenticatedEvidenceRoute: typeof AuthenticatedEvidenceRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLegalDocumentsRoute: typeof AuthenticatedLegalDocumentsRoute
  AuthenticatedLiveRecordingRoute: typeof AuthenticatedLiveRecordingRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOpraHelperRoute: typeof AuthenticatedOpraHelperRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedVoiceNotesRoute: typeof AuthenticatedVoiceNotesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttorneyPortalRoute: AuthenticatedAttorneyPortalRoute,
  AuthenticatedCaseBuilderRoute: AuthenticatedCaseBuilderRoute,
  AuthenticatedCourtPacketRoute: AuthenticatedCourtPacketRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEscalationDetectorRoute: AuthenticatedEscalationDetectorRoute,
  AuthenticatedEvidenceRoute: AuthenticatedEvidenceRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLegalDocumentsRoute: AuthenticatedLegalDocumentsRoute,
  AuthenticatedLiveRecordingRoute: AuthenticatedLiveRecordingRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOpraHelperRoute: AuthenticatedOpraHelperRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedVoiceNotesRoute: AuthenticatedVoiceNotesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AttorneyTokenRoute: AttorneyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
